[project]
name = "runify"
version = "dev"
description = "stuff - cool stuff"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "connexion[flask,swagger-ui]",
    "uvicorn",
    "datamodel-code-generator",
    "psycopg2-binary",
]
