[project]
name = "runify"
version = "dev"
description = "stuff - cool stuff"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn>=0.30.0",
    "slowapi>=0.1.9",
    "pydantic>=2.9.0",
]
